# Generated by Django 3.2.9 on 2021-11-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
