# Generated by Django 3.2.9 on 2021-11-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_title_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
